apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.task.name }}-config
  annotations:
    version: {{ .Values.version }}
  {{ if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{ end }}
data:  
  TASK_TYPE: {{ .Values.task.type }}
  MODEL_CLASS_MAPPING: |
  {{ .Values.task.model.class_mapping | indent 6 }}
  MODEL_CONFIDENCE_THRESHOLD: {{ .Values.task.model.confidence_threshold }}
  WORKER_OPERATING_FPS: {{ .Values.task.worker.operating_fps }}
  WORKER_TRACKER_NAME: {{ .Values.task.worker.tracker.name }}
  WORKER_TRACKER_DISTANCE_FUNCTION: {{ .Values.task.worker.tracker.distance_function }}
  WORKER_TRACKER_DISTANCE_THRESHOLD: {{ .Values.task.worker.tracker.distance_threshold }}