apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.app.name}}-deployment
  annotations:
    version: {{  .Values.version}}
  {{ if .Values.namespace }}    
  namespace: {{  .Values.namespace}}
  {{ end }}    
spec:
  strategy: 
    type: Recreate      
  replicas: {{  .Values.replicas}}
  selector:
    matchLabels:
      app: {{  .Values.app.name}}
  template:
    metadata:
      labels:
        app: {{  .Values.app.name}}      
      annotations:
        version: {{  .Values.version}}
    spec:
      containers:
      - name: {{  .Values.app.name}}
        image: {{  .Values.image}}
        imagePullPolicy: Always
        ports:
        - containerPort: {{  .Values.port}}
