apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.task.name }}-deployment
  annotations:
    version: {{ .Values.version }}
  {{ if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{ end }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      task: {{ .Values.task.name }}
  template:
    metadata:
      labels:
        task: {{ .Values.task.name }}
      annotations:
        version: {{ .Values.version }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: inference-api
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{  .Values.port}}
        resources:
          requests:
            cpu: {{ .Values.cpuRequest }}
            memory: {{ .Values.memoryRequest }}
          limits:
            cpu: {{ .Values.cpuLimit }}
            memory: {{ .Values.memoryLimit }}
        readinessProbe:
          httpGet:
            path: /predict
            port: 8000
        livenessProbe:
          httpGet:
            path: /predict
            port: 8000
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsUser: {{ .Values.runAsUser }}
          runAsGroup: {{ .Values.runAsGroup }}
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        envFrom:
        - configMapRef:
            name: {{ .Values.task.name }}-config
        #read env vars from configmap
        env:
          - name: TASK_TYPE
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: task_type
          - name: MODEL_CLASS_MAPPING
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: model_class_mapping
          - name: MODEL_CONFIDENCE_THRESHOLD
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: model_confidence_threshold
          - name: WORKER_OPERATING_FPS
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_operating_fps
          - name: WORKER_TRACKER_NAME
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_tracker_name
          - name: WORKER_TRACKER_DISTANCE_FUNCTION
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_tracker_distance_function
          - name: WORKER_TRACKER_DISTANCE_THRESHOLD
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_tracker_distance_threshold
          - name: WORKER_CAMERAS
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_cameras
          - name: WORKER_ZONES
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_zones
          - name: WORKER_ZONES_ZONE_BOUNDARY_THRESHOLD
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_zones_zone_boundary_threshold
          - name: WORKER_ZONES_RENTRY_BUFFER_TIME
            valueFrom:
              configMapKeyRef:
                name: platform-config
                key: worker_zones_rentry_buffer_time
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      volumes:
      - name: tmp-volume
        emptyDir: {}  