task:
  name: detection-model
  type: object_detection
  model:
    class_mapping: |
      "TBD"
    confidence_threshold: "TBD"
  worker:
    operating_fps: "TBD"
    tracker: 
      name: "TBD"
      distance_function: "TBD"
      distance_threshold: "TBD"
replicas: 1
port: 8080
image: $IMAGE_NAME:$IMAGE_TAG
version: $VERSION
serviceAccountName: detection-model-sa
imagePullPolicy: Always
cpuRequest: 500m
memoryRequest: 250Mi
cpuLimit: 1000m
memoryLimit: 1000Mi
runAsUser: 10100
runAsGroup: 10100
