apiVersion: scheduler.kalypso.io/v1alpha1
kind: Workload
metadata:
  name: burger-detection
  labels:
    application: kos
    type: model
    task: burger-detection
spec:
  deploymentTargets:
    - name: dev
      labels:
        purpose: dev-test
      environment: dev
      manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: dev
        path: ./burger-detection
    - name: stage
      labels:
        purpose: functional-test
      environment: stage
      manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: stage
        path: ./burger-detection
    - name: prod-gray
      labels:
        purpose: prod
      environment: prod
      manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: prod-gray
        path: ./burger-detection
