apiVersion: scheduler.kalypso.io/v1alpha1
kind: Workload
metadata:
  name: burger-detection
  labels:
    application: kos
    type: model
    task: burger-detection
spec:
  deploymentTargets:
    - name: dev
      labels:
        purpose: dev-test
      environment: dev
      manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: dev
        path: ./burger-detection
    - name: stage
      labels:
        purpose: functional-test
      environment: stage
      manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: stage
        path: ./burger-detection
    - name: prod-gray
      labels:
        purpose: prod
      environment: prod
      manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: prod-gray
        path: ./burger-detection
      configSchemas:
        - |
          {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "title": "Burger Platform Config Schema",
          "description": "Schema for platform config",
          "type": "object",
          "properties": {
            "brand_id": {
              "type": "string",
              "description": "The unified string ID for a brand"
            },
            vision_dayparts {
              "type": "string",
              "description": "Daypart definitions for vision (30 minute slices used to confirm that lighting conditions aren't impacting accuracy)",
            },      
            model_confidence_threshold {
              "type": "number",
              "minimum": 0,
              "maximum": 1,
              "description": "The confidence threshold used to determine if a burger is detected"
            },
            worker_zones {
              "type": "array",
              "description": "The zones that the worker is responsible for",
              "items": {
                "type": "string"
              }
            },
            worker_tracker_distance_threshold {
              "type": "number",
              "description": "The distance threshold used by the worker tracker to determine if a person is in the zone"
            }
          },
            "required": [
            "brand_id",
            "vision_dayparts",
            "model_class_mapping",
            "worker_zones",
            "worker_tracker_distance_threshold"
            ]              
          }	