apiVersion: scheduler.kalypso.io/v1alpha1
kind: Workload
metadata:
  name: tacos-burritos-ml
  labels:
    type: ml-model
spec:
  deploymentTargets:
    - name: dev1
      labels:
        purpose: dev-functional-test
        application: dm
        zone: gray
        type: model
      environment: dev
      manifests:
        repo: https://github.com/eedorenko/mlops-gitops-gitops
        branch: dev
        path: ./tacos-burritos-ml
